# Generated by Django 3.0.8 on 2020-07-30 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(default=' ', max_length=100)),
                ('trip_name', models.CharField(default=' ', max_length=150)),
                ('x_loc', models.FloatField(default=0, null=True)),
                ('y_loc', models.FloatField(default=0, null=True)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_x', models.FloatField(default=0, null=True)),
                ('loc_y', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_name', models.CharField(default='User', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IP', 'In Progress'), ('CP', 'Completed')], max_length=50)),
                ('price', models.FloatField()),
                ('cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uber.Cab')),
                ('dest_loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_dest', to='uber.Location')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='uber.Rider')),
                ('src_loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_src', to='uber.Location')),
            ],
        ),
    ]
