# Generated by Django 3.0.8 on 2020-07-29 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(default='', max_length=200)),
                ('step_desc', models.CharField(default='', max_length=300)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(default='', max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('segment', models.CharField(choices=[('Today', 'My Day'), ('Imp', 'Important'), ('Planned', 'Planned'), ('Assigned', 'Assigned To Me'), ('Flagged', 'Flagged Email')], default='Today', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('steps', models.ManyToManyField(to='todo.Step')),
            ],
        ),
    ]
